apiVersion: v1
kind: Pod
metadata:
  labels:
    run: eni-todo
  name: eni-todo-mariadb
spec:
  containers:
  - image: eni-todo:tomcat-mariadb-env
    imagePullPolicy: IfNotPresent
    name: eni-todo
    env:
    - name: SPRING_PROFILES_ACTIVE
      value: "tomcat-mariadb-env"
    - name: DB_DTB_USERNAME
      value: "springuser"
    - name: DB_DTB_PASSWORD
      value: "mypassword-quoor-uHoe7z"
    - name: DB_DTB_JDBC_URL
      value: "jdbc:mysql://mariadb:3306/db_todo"
    - name: MULTIPART_LOCATION
      value: "/usr/local/tomcat/files"
    ports:
      - name: http8080 
        containerPort: 8080
        protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
