apiVersion: v1
kind: Service
metadata:
  labels:
    app: ext-mariadb
  name: mariadb
spec:
  ports:
  - port: 3306
    name: mariadb
    protocol: TCP
    targetPort: 3306
  type: ClusterIP

---
apiVersion: v1
kind: Endpoints
metadata:
  # On ne mets de labels pour mettre en avant 
  # que le liens service--endpoint est sur 
  #le nom et non sur les labels
  #labels:
  #  app: ext-mariadb
  name: mariadb
  namespace: example
subsets:
- addresses:
  - ip: 192.168.99.128
  ports:
  - name: mariadb
    port: 3306
    protocol: TCP