apiVersion: v1
kind: Pod
metadata:
  labels:
    run: eni-todo-h2
  name: eni-todo-h2
spec:
  containers:
  - image: eni-todo-tomcat-h2:latest
    imagePullPolicy: IfNotPresent
    name: eni-todo-h2
    ports:
      - name: http8080 
        containerPort: 8080
        protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
