apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mariadb-galera
spec:
  rootPasswordSecretKeyRef:
    name: mariadb
    key: root-password
  username: springuser
  database: db_todo
  passwordSecretKeyRef:
    name: mariadb
    key: password    

  replicas: 3

  storage:
    size: 1Gi
    storageClassName: galera-pv
  
  galera:
    enabled: true
    primary:
      podIndex: 0
      automaticFailover: true
    recovery:
      enabled: true
    config:
      reuseStorageVolume: true
      volumeClaimTemplate:
        storageClassName: galera-pv
        resources:
          requests:
            storage: 300Mi
        accessModes:
          - ReadWriteOnce

  service:
    type: LoadBalancer

  primaryService:
    type: LoadBalancer

  secondaryService:
    type: LoadBalancer

  metrics:
    enabled: false
    
  myCnf: |
    [mariadb]
    bind-address=*
    default_storage_engine=InnoDB
    binlog_format=row
    innodb_autoinc_lock_mode=2
    max_allowed_packet=256M
    
  podSecurityContext:
    runAsUser: 10000
    fsGroup: 10000


