apiVersion: v1
kind: Namespace
metadata:
  name: eni-todo
  labels:
    app: eni-todo
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: eni-todo-sa
  namespace: eni-todo
  labels:
    app: eni-todo
---
# this should be tuned to have a more reduce access
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: view
  namespace: eni-todo
  labels:
    app: eni-todo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: ServiceAccount
  name: eni-todo-sa
  namespace: eni-todo
