apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: eni-todo-claim
  namespace: eni-todo
  labels:
    app: eni-todo
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

